services:
    mongo:
        image: mongo
        restart: always
        logging:
            driver: none
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 10s

    backend-test:
        build:
            context: backend
            dockerfile: ../Dockerfile.backend
        environment:
            DB_ADDRESS: mongodb://mongo:27017/mestodb
        command: npm run lint
        restart: "no"
        depends_on:
            mongo:
                condition: service_healthy

    backend:
        build:
            context: backend
            dockerfile: ../Dockerfile.backend
        environment:
            DB_ADDRESS: mongodb://mongo:27017/mestodb
        depends_on:
            mongo:
                condition: service_healthy
        ports:
            - 3001:3000
        healthcheck:
            interval: 10s
            timeout: 2s
            start_period: 15s
            retries: 5
            test: node healthcheck.js

    auth:
        build:
            context: frontend
            dockerfile: ./services/auth/Dockerfile
        ports:
            - "3004:3004"
        depends_on:
            - backend
        environment:
            - port=3004

    profile:
        build:
            context: frontend
            dockerfile: ./services/profile/Dockerfile
        ports:
            - "3003:3003"
        depends_on:
            - backend
        environment:
            - port=3003

    gallery:
        build:
            context: frontend
            dockerfile: ./services/gallery/Dockerfile
        ports:
            - "3002:3002"
        depends_on:
            - backend
        environment:
            - port=3002

    frontend:
        build:
            context: frontend
            dockerfile: ./Dockerfile
        ports:
            - 3000:3000
        environment:
            - AUTH_REMOTE_URL=http://auth:3004
            - PROFILE_REMOTE_URL=http://profile:3003
            - GALLERY_REMOTE_URL=http://gallery:3002
        depends_on:
            backend:
                condition: service_healthy
            auth:
                condition: service_started
            profile:
                condition: service_started
            gallery:
                condition: service_started
